// this file is auto-generated by the specmatic gradle plugin. Any changes will be lost!
package io.specmatic.junit5.support

object VersionInfo {
    val version = "2.7.5-SNAPSHOT"
    val gitCommit = "6679a404ba5467b3607279cac7d9bee7df015dfa"
    val gitShortCommit = "6679a404"
    val group = "io.specmatic"
    val name = "junit5-support"
    
    
    fun describe() = "v2.7.5-SNAPSHOT(6679a404)"
}