<definitions targetNamespace="http://localhost/child">
    <import location="grandChild.wsdl" namespace="http://localhost/grandChild"/>
    <types>
        <schema targetNamespace="http://localhost/schema">
            <import schemaLocation="childSchema.xsd" namespace="http://localhost/childSchema"/>
        </schema>
    </types>
</definitions>