// this file is auto-generated by the specmatic gradle plugin. Any changes will be lost!
package io.specmatic

object VersionInfo {
    val version = "2.7.5-SNAPSHOT"
    val gitCommit = "3b961a231e05b51bdc40423273c4b10e6f580ec8"
    val gitShortCommit = "3b961a23"
    val group = "io.specmatic"
    val name = "specmatic"
    
    
    fun describe() = "v2.7.5-SNAPSHOT(3b961a23)"
}